index:
    path: /dev
    controller: App\Controller\DefaultController::index

index_without_dev:
    path: /
    controller: App\Controller\DefaultController::index

upload:
    path: /dev/upload
    controller: App\Controller\DefaultController::upload

upload_without_dev:
    path: /upload
    controller: App\Controller\DefaultController::upload

download:
    path: /dev/download
    controller: App\Controller\DefaultController::download

download_without_dev:
    path: /download
    controller: App\Controller\DefaultController::download
